.vscode/extensions.json, frontend/.prettierrc, frontend/package.json, frontend/pnpm-lock.yaml, frontend/postcss.config.js, frontend/src/app.pcss, frontend/src/routes/+layout.svelte, frontend/src/routes/+layout.ts, frontend/src/routes/+page.svelte, frontend/src/routes/+page.ts, frontend/tailwind.config.js, frontend/tsconfig.json
- базовая настройка тейлвинда
- базовая настройка svelte-query + пример клиентского вызова и гибридного вызова( с пререндером)
- апдейтнул все депсы до последней версии - у темплейта довольно устаревшие
- добавил пару более строгих настроек в тс конфиге
- добавил рекомендуюемые плагины для ВСКода
=> Tanstack, tailwind, deps update, stricter tsconfig

frontend/.prettierrc, frontend/Dockerfile, frontend/package.json, frontend/pnpm-lock.yaml, frontend/postcss.config.js, frontend/src/app.html, frontend/src/routes/+layout.svelte, frontend/src/routes/+page.svelte, frontend/src/routes/auth/login/+page.svelte, frontend/src/routes/profile/matches/+layout.svelte, frontend/src/routes/profile/matches/+page.svelte, frontend/src/routes/profile/matches/[id]/+page.svelte, frontend/src/routes/profile/matches/getChats.ts
=> Matches page

backend/app/api/routers/user.py, backend/app/api/schemas/user.py, backend/app/db/engine.py, backend/app/main.py, backend/app/models/mixin.py, backend/app/models/user.py, backend/requirements.txt
сделал подключение к базе через beanie 
определил модель User, которая наследутеся от UUIDMixin(миксин, где генерируется UUID)
=> Issue32 beanie

backend/app/api/routers/cv.py, backend/app/api/routers/user.py, backend/app/api/routers/vacancy.py, backend/app/api/schemas/cv.py, backend/app/db/engine.py, backend/app/exceptions.py, backend/app/main.py, backend/app/models/cv.py, backend/app/models/mixin.py, backend/app/models/user.py, backend/app/models/vacancy.py
Issue #19:
1. Добавил общие классы в Mixin, небольшой рефактор базового класса
2. Выделил в отдельный модуль exceptions handler
3. Добавил endpoint для CV
=> Add cv endpoint, exceptoin module

backend/app/api/routers/cv.py, backend/app/api/routers/vacancy.py, backend/app/api/schemas/vacancy.py, backend/app/db/engine.py, backend/app/main.py, backend/app/models/vacancy.py
=> Add mock vacancy: endpoints, models, schema

backend/app/api/routers/cv.py, backend/app/api/routers/cv_note.py, backend/app/api/schemas/cv_note.py, backend/app/db/engine.py, backend/app/main.py, backend/app/models/cv_note.py, backend/app/models/mixin.py
=> Add cv note endpoints

backend/app/api/routers/__init__.py, backend/app/api/routers/cv.py, backend/app/api/routers/cv_note.py, backend/app/api/schemas/cv_note.py, backend/app/db/engine.py, backend/app/main.py, backend/app/models/cv_note.py, backend/app/models/mixin.py
Перенес логику роутинга в init папки routers
=> Move routers logic

frontend/package.json, frontend/scripts/tsconfig.json
Fixes error "no tsconfig found"
=> Docker-dev script hotfix

backend/app/api/routers/__init__.py, backend/app/api/routers/vacancy_note.py, backend/app/api/schemas/vacancy_note.py, backend/app/db/engine.py, backend/app/models/vacancy_note.py
=> vacancy notes

backend/app/api/routers/__init__.py, backend/app/api/routers/collection.py, backend/app/db/models/mixins/__init__.py, backend/app/db/models/mixins/grade.py, backend/app/db/models/mixins/mixin.py, backend/app/db/models/vacancy.py, backend/app/db/models/vacancy_note.py
=> Add grade endpoint

backend/app/api/routers/collection.py, backend/app/db/models/mixins/__init__.py, backend/app/db/models/mixins/mixin.py, backend/app/db/models/mixins/title.py
=> Add title endpoint

README/for-developers.md
=> fix for-developers readme typos, add links

.gitignore, backend/app/api/routers/auth.py, backend/app/api/routers/cv.py, backend/app/api/routers/user.py, backend/app/api/routers/vacancy.py, backend/app/api/schemas/base/__init__.py, backend/app/api/schemas/base/cv_vacancy.py, backend/app/api/schemas/user.py, backend/app/db/models/mixins/__init__.py, backend/app/db/models/mixins/role.py, backend/app/db/models/user.py, backend/app/repository/services/user.py, backend/app/unitorwork/__init__.py, backend/app/unitorwork/dependencies.py, backend/app/unitorwork/interfaces/base.py, backend/app/unitorwork/services/__init__.py, backend/app/unitorwork/services/cv_vacancy_uow.py, backend/tests/conftest.py, backend/tests/cv/test_cv.py, backend/tests/users/test_users.py
=> Update User model

backend/app/db/engine.py, backend/app/db/models/match.py, backend/app/repository/interfaces/base.py, backend/app/repository/interfaces/mongo_rep.py, backend/app/repository/repositories/__init__.py, backend/app/repository/repositories/match_repo.py, backend/app/repository/services/__init__.py, backend/app/repository/services/match.py, backend/app/unitorwork/interfaces/base.py, backend/app/unitorwork/services/match_uow.py
=> Add match model feature

backend/app/api/routers/cv.py, backend/app/api/routers/vacancy.py, backend/app/services/__init__.py, backend/app/services/dependencies.py, backend/app/services/interfaces/__init__.py, backend/app/services/interfaces/base.py, backend/app/services/record_handler.py, backend/app/services/repository/interfaces/base.py, backend/app/services/repository/interfaces/mongo_rep.py, backend/app/services/repository/services/match.py, backend/app/services/repository/services/user.py, backend/app/services/repository/services/vacancy_cv.py, backend/app/services/repository/services/vacancy_cv_note.py, backend/app/services/unitorwork/services/match_uow.py
=> Update random endpoints

.github/workflows/linters.yml, frontend/package.json, frontend/src/routes/create/cv/+page.svelte, frontend/src/routes/documents/cookie-policy/+page.svelte, frontend/src/routes/documents/privacy-policy/+page.svelte, frontend/src/routes/documents/terms-of-service/+page.svelte, frontend/src/routes/integrations/+page.svelte, frontend/src/routes/user/+page.svelte
Added linters to CI/CD
Closes #236 
-
---
Backend:
- [] The ERD-diagram updated, if any related model changed/added
- [] Tests updated/added  
- [] Separate task for updating related test created and assigned
---
=> add linters to cicd

backend/app/api/routers/__init__.py, backend/app/api/routers/chat.py, backend/app/api/schemas/chat.py, backend/app/db/engine.py, backend/app/db/models/chat.py, backend/app/db/models/chat_message.py, backend/app/services/repository/__init__.py, backend/app/services/repository/dependencies.py, backend/app/services/repository/interfaces/base.py, backend/app/services/repository/interfaces/mongo_rep.py, backend/app/services/repository/repositories/__init__.py, backend/app/services/repository/repositories/chat_message_repo.py, backend/app/services/repository/repositories/chat_repo.py, backend/app/services/repository/services/__init__.py, backend/app/services/repository/services/chat.py, backend/app/services/repository/services/chat_message.py
Chat mock endpoint added.
Issue24
[Add any additional information or context that might be helpful for reviewers.]
---
Backend:
---
=> Issue24 chat mock endpoint

README.md
Fix linter badge in README
No issue
=> Fix linter badge in README

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Added bug repost and feature template for GitHub
=> Add issue templates feature

.vscode/settings.json, backend/app/api/routers/auth.py, backend/app/config.py, dev.sh, frontend/src/lib/components/Header.svelte, frontend/src/lib/components/header/Header.svelte, frontend/src/lib/components/header/LogoutModal.svelte, frontend/src/routes/+layout.svelte, frontend/src/routes/auth/login/+page.svelte, tests/api_testing/src/test_ping.py, tests/api_testing/src/users/test_all_users.py, tests/e2e_testing/src/start_page/test_go_to_survey_button.py
Closes #352
Closes #351
Closes #356
Closes #347 
---
Backend:
---
=> Init mobile view

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/lib/components/header/Header.svelte
Поправлена сборка фронта в прод режиме
=> fix building

backend/app/services/unitorwork/services/match_uow.py
Add user checking in match preparation.
=> Add owner checking while matches preparing

backend/app/api/routers/cv.py, backend/app/api/routers/relation.py, backend/app/api/routers/user.py, backend/app/api/routers/vacancy.py, backend/app/services/record_handler.py, backend/app/services/repository/services/vacancy_cv.py, backend/app/services/unitorwork/services/cv_vacancy_uow.py
Routing permissions were updated:
- Unnecessary user routings - hidden
- GET routing for CV and Vacancy require authorization
=> Update routing permissions

backend/app/api/routers/auth.py
=> Fix router for auth

backend/app/api/routers/auth.py
Reverts roll-over/unknown-interview#395
=> Revert "Fix router for auth"

frontend/src/routes/+page.svelte, frontend/src/routes/[type=type]/create/+page.svelte, frontend/src/routes/[type=type]/create/Skills.svelte, frontend/src/routes/[type=type]/match/+layout.svelte, frontend/src/routes/[type=type]/match/Chip.svelte, frontend/src/routes/[type=type]/match/[id]/+page.svelte, frontend/src/routes/auth/login/+page.svelte, frontend/src/routes/purpose/+page.svelte
=> fix adaptive + add dark logo

frontend/src/lib/components/RadioGroup.svelte, frontend/src/lib/components/header/Header.svelte, frontend/src/routes/[type=type]/create/+page.svelte, frontend/src/routes/[type=type]/create/Profession.svelte, frontend/src/routes/[type=type]/create/Skills.svelte, frontend/src/routes/[type=type]/match/+layout.svelte, frontend/src/routes/[type=type]/match/Chip.svelte, frontend/src/routes/[type=type]/match/Match.svelte, frontend/src/routes/[type=type]/match/[id]/+page.svelte
=> feat: backend integration profession/skills list + fix style
